sudo: false
language: rust
cache: cargo
matrix:
    allow_failures:
        - os: windows
        - os: linux
    include:
        - os: linux
          dist: xenial
          rust: stable
        - os: osx
          osx_image: xcode9.4
          rust: stable
        - os: windows
          rust: stable

script:
  - cargo build --verbose
