[package]
name = "pbrt_rs"
version = "0.0.1"
authors = ["Adrien Gruson <adrien.gruson@gmail.com>"]

[[bin]]
name = "pbrt_rs"
doc = false

[dependencies]
pest = "^1.0.0-beta"
pest_derive = "^1.0.0-beta"
clap = "2.31.1"
env_logger = "0.5.6"
log = "0.4.0"
cgmath = "0.16.1"
ply-rs = "0.1.1"