[package]
name = "viewer"
version = "0.0.1"
authors = ["Adrien Gruson <adrien.gruson@gmail.com>"]
edition = "2018"

[dependencies]
pbrt_rs = { path = "../../" }
cgmath = "*"
clap = "*"
env_logger = "*"
log = "*"
byteorder = "*"
pbr = "*"
rayon = "*"